import { StyleSheet, Platform } from 'react-native';

export const getExpensesStyles = (colors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  mainScrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 100,
  },

  // HEADER STYLING MATCHING ORIGINAL IMAGE PERFECTLY
  headerSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  headerContent: {
    flex: 1,
  },
  title: {
    fontSize: 26,
    fontWeight: '800',
    color: colors.text,
    marginBottom: 2,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconActionButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.card,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.cardBorderMedium,
  },
  iconActionButtonActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  createButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    gap: 4,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  createButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#ffffff',
  },

  // TIMEFRAME CONTROLS
  pillControlRow: {
    marginBottom: 16,
  },
  pillContainer: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceAlt,
    borderRadius: 14,
    padding: 4,
  },
  pillItem: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  pillItemActive: {
    backgroundColor: colors.card,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  pillText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  pillTextActive: {
    color: colors.text,
    fontWeight: '700',
  },

  // BOARD STATS
  statsCard: {
    flexDirection: 'row',
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingVertical: 14,
    marginBottom: 16,
  },
  statBox: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  statValue: {
    fontSize: 13,
    fontWeight: '800',
    marginTop: 4,
  },

  // INTERACTIVE CONFIG POPUP CONTAINER ELEMENTS
  datesRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  dateInputWrapper: {
    flex: 1,
  },
  dateLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  datePickerInputGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 8,
    paddingHorizontal: 8,
    height: 38,
  },
  dateInlineInput: {
    width: 24,
    height: '100%',
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
    textAlign: 'center',
    padding: 0,
  },
  dateSlash: {
    fontSize: 12,
    color: colors.textMuted,
    fontWeight: '600',
  },
  typesRow: {
    borderTopWidth: 1,
    borderTopColor: colors.cardBorder,
    paddingTop: 14,
    marginBottom: 20,
  },
  typeSelectorLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  typeButtonsRow: {
    flexDirection: 'row',
    gap: 6,
  },
  typeSelectBtn: {
    flex: 1,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 8,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  typeSelectBtnActive: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.primary,
  },
  typeSelectText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  typeSelectTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  applyFilterButton: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  applyFilterButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  resetTextLink: {
    fontSize: 12,
    color: '#ef4444',
    fontWeight: '700',
  },
  resetTextLinkQuick: {
    fontSize: 12,
    color: '#ef4444',
    fontWeight: '600',
  },

  // LIST CONTAINER RENDER ROWS
  transactionsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    marginTop: 4,
  },
  transactionsTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  transactionsContainer: {
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: 14,
  },
  txRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  txAvatarCircle: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  txTitleText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
  },
  txMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 3,
    gap: 6,
  },
  txCatBadge: {
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 4,
  },
  txCatBadgeText: {
    fontSize: 9,
    fontWeight: '700',
  },
  txDateText: {
    fontSize: 10,
    color: colors.textMuted,
    fontWeight: '500',
  },
  txAmountText: {
    fontSize: 13,
    fontWeight: '800',
  },
  txTypeText: {
    fontSize: 8,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
    marginTop: 1,
  },

  // EMPTY LIST CONTROLS
  emptyStateCard: {
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingVertical: 36,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyStateIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  emptyStateTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 4,
  },
  emptyStateSubtitle: {
    fontSize: 12,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 16,
    paddingHorizontal: 16,
    marginBottom: 16,
  },

  // FAB 
  fabButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
    zIndex: 99,
  },

  // SHEET MODAL BACKDROPS
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
    justifyContent: 'flex-end',
  },
  addSheet: {
    backgroundColor: colors.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '88%',
    minHeight: '45%',
    paddingBottom: Platform.OS === 'ios' ? 34 : 16, // Proper safe area bottom padding
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  sheetTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
  },
  sheetScroll: {
    flex: 1,
  },
  sheetScrollContent: {
    paddingHorizontal: 20,
    paddingTop: 14,
  },
  modalAmountHeader: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    marginBottom: 14,
  },
  modalAmountLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  modalAmountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalAmountCurrency: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.primary,
    marginRight: 4,
    marginTop: 2,
  },
  modalAmountInput: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.text,
    padding: 0,
    minWidth: 80,
    textAlign: 'center',
  },
  modalPillContainer: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceAlt,
    borderRadius: 14,
    padding: 3,
    marginBottom: 14,
  },
  modalPill: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 10,
  },
  modalPillActive: {
    backgroundColor: colors.card,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  modalPillText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  modalPillTextActive: {
    color: colors.primary,
  },
  modalFormCard: {
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: 14,
    marginBottom: 14,
  },
  modalFormRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  modalRowLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    width: 76,
  },
  modalRowInput: {
    flex: 1,
    fontSize: 12,
    color: colors.text,
    fontWeight: '600',
    padding: 0,
    textAlign: 'right',
  },
  modalRowValue: {
    flex: 1,
    fontSize: 12,
    color: colors.text,
    fontWeight: '600',
    textAlign: 'right',
    marginRight: 4,
  },
  notesLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 2,
  },
  notesTextInput: {
    fontSize: 12,
    color: colors.text,
    fontWeight: '500',
    padding: 0,
    marginTop: 2,
    textAlignVertical: 'top',
    height: 40,
  },
  catChipsContainer: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
  },
  catChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  catChipText: {
    fontSize: 10,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  receiptRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: colors.cardBorder,
  },
  receiptLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  receiptAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primaryLight,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 4,
  },
  receiptAddText: {
    fontSize: 11,
    color: colors.primary,
    fontWeight: '700',
  },
  receiptThumbnailContainer: {
    position: 'relative',
  },
  receiptThumbnail: {
    width: 34,
    height: 34,
    borderRadius: 6,
    resizeMode: 'cover',
  },
  receiptRemoveBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#ef4444',
    width: 14,
    height: 14,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetFooter: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.cardBorder,
    gap: 10,
  },
  sheetCancelBtn: {
    flex: 1,
    height: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.card,
  },
  sheetCancelBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  sheetSaveBtn: {
    flex: 2,
    height: 42,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetSaveBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#ffffff',
  },

  // TIME CONFIG WINDOW OVERLAYS
  dateSubOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  dateSubSheet: {
    backgroundColor: colors.card,
    borderRadius: 16,
    paddingBottom: 16,
  },
  pickerSection: {
    padding: 16,
    alignItems: 'center',
  },
  pickerSubLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textSecondary,
    alignSelf: 'flex-start',
    marginBottom: 4,
    marginTop: 8,
  },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  pickerInput: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: 8,
    width: 40,
    height: 36,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  pickerSeparator: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textSecondary,
    marginHorizontal: 4,
  },
  saveDateButton: {
    backgroundColor: colors.primary,
    width: '100%',
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 12,
  },
  saveDateButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
});

