import { StyleSheet, Platform } from 'react-native';

const getCreateSceneStyles = (colors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 14,
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  backBtn: {
    padding: 6,
  },
  headerActionBtn: {
    minWidth: 78,
    height: 38,
    borderRadius: 19,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    gap: 6,
  },
  headerActionBtnDisabled: {
    backgroundColor: colors.inputBorder,
  },
  headerActionText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#ffffff',
  },
  headerActionTextDisabled: {
    color: colors.textMuted,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },

  // 1. Large Amount Header
  amountHeaderContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    marginBottom: 16,
  },
  amountHeaderLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
  },
  amountInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  amountCurrencySymbol: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.primary,
    marginRight: 6,
    marginTop: 4,
  },
  amountTextInput: {
    fontSize: 34,
    fontWeight: '800',
    color: colors.text,
    padding: 0,
    minWidth: 100,
    textAlign: 'center',
  },

  // 2. Active Group Settings Tile
  groupTile: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: colors.primaryBorder,
    marginBottom: 16,
  },
  groupIndicator: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 12,
  },
  groupTileLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
  },
  groupTileValue: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
    marginTop: 2,
  },
  changeGroupText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
    marginRight: 4,
  },

  // 3. Settings List-Style Card panel
  formCard: {
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.01,
    shadowRadius: 6,
    elevation: 1,
  },
  formRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  rowIcon: {
    marginRight: 12,
  },
  rowLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textSecondary,
    width: 90,
  },
  rowInput: {
    flex: 1,
    fontSize: 14,
    color: colors.text,
    fontWeight: '600',
    padding: 0,
    textAlign: 'right',
  },
  rowTextVal: {
    flex: 1,
    fontSize: 14,
    color: colors.text,
    fontWeight: '600',
    textAlign: 'right',
    marginRight: 4,
  },
  inlineActionBtn: {
    padding: 4,
    marginLeft: 6,
  },

  // 4. Notes & Compact Receipt Capture Card
  notesLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 4,
  },
  notesTextInput: {
    fontSize: 14,
    color: colors.text,
    fontWeight: '500',
    padding: 0,
    marginTop: 6,
    textAlignVertical: 'top',
    height: 48,
  },
  receiptRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: colors.cardBorder,
  },
  receiptLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  receiptAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primaryLight,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 4,
  },
  receiptAddText: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: '700',
  },
  receiptThumbnailContainer: {
    position: 'relative',
  },
  receiptThumbnail: {
    width: 44,
    height: 44,
    borderRadius: 6,
    resizeMode: 'cover',
    borderWidth: 1,
    borderColor: colors.inputBorder,
  },
  receiptRemoveBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#ef4444',
    width: 14,
    height: 14,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Fixed Floating Footer (iOS standard)
  fixedFooter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.card,
    borderTopWidth: 1,
    borderTopColor: colors.cardBorder,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 24 : 12,
    flexDirection: 'row',
    gap: 12,
  },
  cancelBtnFoot: {
    flex: 1,
    height: 46,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.card,
  },
  cancelBtnTextFoot: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  submitBtnFoot: {
    flex: 2,
    height: 46,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#06b6d4',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  submitBtnDisabled: {
    opacity: 0.5,
    backgroundColor: colors.textMuted,
    shadowOpacity: 0,
  },
  submitBtnTextFoot: {
    fontSize: 14,
    fontWeight: '700',
    color: '#ffffff',
  },

  // Modal bottoms
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'flex-end',
  },
  bottomSheet: {
    backgroundColor: colors.card,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '75%',
    minHeight: '40%',
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  sheetTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  groupOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  activeGroupOptionRow: {
    backgroundColor: colors.primaryLight,
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  groupColorIndicator: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 10,
  },
  groupOptionText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.textSecondary,
  },
  activeGroupOptionText: {
    color: colors.primary,
    fontWeight: '700',
  },

  // DateTime selector
  pickerSection: {
    padding: 20,
    alignItems: 'center',
  },
  pickerSubLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    alignSelf: 'flex-start',
    marginBottom: 6,
    marginTop: 10,
  },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  pickerInput: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: 8,
    width: 44,
    height: 40,
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
  },
  pickerSeparator: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textSecondary,
    marginHorizontal: 6,
  },
  periodToggle: {
    flexDirection: 'row',
    backgroundColor: colors.inputBorder,
    borderRadius: 8,
    padding: 2,
    marginLeft: 14,
  },
  periodBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
  },
  periodBtnActive: {
    backgroundColor: colors.card,
  },
  periodText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  periodTextActive: {
    color: colors.primary,
  },
  quickDateRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  quickDateBtn: {
    backgroundColor: colors.primaryLight,
    borderWidth: 1,
    borderColor: colors.primaryBorder,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  quickDateText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
  },
  saveDateButton: {
    backgroundColor: colors.primary,
    width: '100%',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  saveDateButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },

  // Member checklist
  memberCheckRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: colors.card,
    borderRadius: 12,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  memberCheckName: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
    flex: 1,
    letterSpacing: -0.1,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: colors.inputBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  closeMembersBtn: {
    backgroundColor: colors.primary,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 16,
  },
  closeMembersBtnText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },

  // Map Simulator Modal layout
  mapSafeArea: {
    flex: 1,
    backgroundColor: colors.card,
  },
  mapSheet: {
    flex: 1,
    backgroundColor: colors.background,
  },
  mapSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  mapSheetTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  mapSearchContainer: {
    padding: 12,
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
    zIndex: 10,
  },
  mapSearchInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 40,
  },
  mapSearchInput: {
    flex: 1,
    fontSize: 13,
    color: colors.text,
    fontWeight: '500',
  },
  autocompleteList: {
    backgroundColor: colors.card,
    borderRadius: 10,
    marginTop: 8,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 3,
  },
  autocompleteItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  autocompleteName: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
  },
  autocompleteAddress: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 1,
  },
  mapVisualContainer: {
    flex: 1,
    backgroundColor: '#e2e8f0',
    position: 'relative',
    overflow: 'hidden',
  },
  roadHorizontal1: {
    position: 'absolute',
    top: '30%',
    left: 0,
    right: 0,
    height: 24,
    backgroundColor: '#ffffff',
  },
  roadHorizontal2: {
    position: 'absolute',
    bottom: '40%',
    left: 0,
    right: 0,
    height: 32,
    backgroundColor: '#ffffff',
  },
  roadVertical1: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: '25%',
    width: 24,
    backgroundColor: '#ffffff',
  },
  roadVertical2: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: '30%',
    width: 32,
    backgroundColor: '#ffffff',
  },
  parkBlock: {
    position: 'absolute',
    top: '5%',
    right: '5%',
    width: '40%',
    height: '20%',
    backgroundColor: '#dcfce7',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#bbf7d0',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  parkText: {
    fontSize: 10,
    color: '#166534',
    fontWeight: '700',
  },
  landmark: {
    position: 'absolute',
    backgroundColor: colors.card,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  landmarkText: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  mapPinContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: -21,
    marginTop: -42,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 5,
  },
  mapPinDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.text,
    marginTop: -6,
  },
  myLocationFab: {
    position: 'absolute',
    bottom: 180,
    right: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.card,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
    zIndex: 15,
  },
  mapFooterCard: {
    backgroundColor: colors.card,
    padding: 16,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 5,
  },
  mapFooterInfo: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  mapFooterName: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
  },
  mapFooterAddress: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 2,
    lineHeight: 14,
  },
  mapConfirmButton: {
    backgroundColor: colors.primary,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  mapConfirmText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },

  // 5. Split Configuration Section
  splitSection: {
    backgroundColor: colors.card,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    padding: 16,
    marginBottom: 20,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.02,
    shadowRadius: 12,
    elevation: 2,
  },
  splitSectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: -0.2,
  },
  splitSectionSubtitle: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '400',
    marginTop: 2,
    marginBottom: 14,
    lineHeight: 16,
  },
  pillTabsContainer: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceAlt,
    borderRadius: 10,
    padding: 3,
    marginBottom: 14,
  },
  pillTab: {
    flex: 1,
    paddingVertical: 7,
    alignItems: 'center',
    borderRadius: 7,
  },
  activePillTab: {
    backgroundColor: colors.card,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  pillTabText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  activePillTabText: {
    color: colors.primary,
  },
  memberSelectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primaryLight,
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 40,
    marginBottom: 14,
  },
  memberSelectorText: {
    fontSize: 13,
    color: colors.primary,
    fontWeight: '600',
    marginLeft: 6,
  },
  emptyPrompt: {
    paddingVertical: 14,
    alignItems: 'center',
  },
  emptyPromptText: {
    fontSize: 12,
    color: colors.textMuted,
    fontWeight: '400',
  },
  emptyGroupsState: {
    paddingVertical: 16,
    alignItems: 'center',
  },
  emptyGroupsText: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  membersSplitCard: {
    gap: 8,
  },

  // MEMBER LIST ROW
  memberListRow: {
    flexDirection: 'column',
    alignItems: 'stretch',
    backgroundColor: colors.card,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    marginBottom: 2,
  },

  // TOP ROW
  memberTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 10,
  },
  memberAvatarWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 6,
  },
  memberNameCol: {
    flex: 1,
    marginLeft: 10,
    justifyContent: 'center',
  },

  // AVATARS
  memberAvatarCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: '12',
  },
  memberAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 18,
  },
  avatarTextLetter: {
    fontSize: 13,
    fontWeight: '700',
    color: '#ffffff',
  },

  // TYPOGRAPHY FOR NAMES
  memberNameText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: -0.1,
  },
  smallMetaRow: {
    marginTop: 1,
  },
  smallMetaText: {
    fontSize: 11,
    color: colors.textMuted,
    fontWeight: '400',
  },
  memberRightCol: {
    alignItems: 'flex-end',
    justifyContent: 'center',
  },

  // FINANCIAL AMOUNTS
  equalSplitText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
    textAlign: 'right',
  },
  sharingRightCol: {
    alignItems: 'flex-end',
    justifyContent: 'center',
  },

  shareSubLabel: {
    fontSize: 10,
    color: colors.textMuted,
    fontWeight: '600',
    textAlign: 'right',
    letterSpacing: 0.2,
    textTransform: 'uppercase',
  },

  // BOTTOM ROW INPUT CHIPS
  memberInputsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    width: '100%',
  },
  memberInputField: {
    flex: 1,
  },
  memberInputLabel: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.textMuted,
    marginBottom: 3,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  memberInputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderRadius: 8,
    paddingHorizontal: 8,
    height: 32,
  },
  memberInputCurrency: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textSecondary,
    marginRight: 2,
    includeFontPadding: false,
  },
  memberInputText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
    padding: 0,
    margin: 0,
    height: '100%',
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  individualInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderRadius: 8,
    paddingHorizontal: 8,
    width: 80,
    height: 32,
  },
  indivCurrency: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textSecondary,
    marginRight: 2,
    includeFontPadding: false,
  },
  indivInputBox: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
    height: '100%',
    padding: 0,
    margin: 0,
    textAlign: 'right',
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  additionalBadge: {
    backgroundColor: colors.successLight,
    paddingHorizontal: 5,
    paddingVertical: 1.5,
    borderRadius: 4,
    marginLeft: 4,
  },
  additionalText: {
    color: '#10b981',
    fontSize: 10,
    fontWeight: '600',
  },
  paidRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  paidLabelWrap: {
    marginRight: 4,
    justifyContent: 'center',
  },
  paidLabel: {
    fontSize: 11,
    color: colors.textMuted,
    fontWeight: '500',
  },
  paidInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  paidCurrency: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '600',
    marginRight: 2,
  },
  paidInputBox: {
    width: 48,
    paddingVertical: 0,
    paddingHorizontal: 0,
    textAlign: 'right',
    fontWeight: '600',
    color: colors.text,
    fontSize: 13,
  },
  statusBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    marginTop: 10,
    gap: 6,
  },
  bannerOk: {
    backgroundColor: colors.successLight,
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  bannerUnder: {
    backgroundColor: colors.warningLight,
    borderWidth: 1,
    borderColor: '#fef08a',
  },
  bannerOver: {
    backgroundColor: colors.errorLight,
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  statusBannerText: {
    fontSize: 12,
    fontWeight: '600',
  },
  textOk: { color: colors.success },
  textUnder: { color: colors.warning },
  textOver: { color: colors.error },

  adminNoticeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.warningLight,
    borderWidth: 1,
    borderColor: '#ffedd5',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    marginTop: 8,
    marginBottom: 8,
  },
  adminNoticeText: {
    fontSize: 11,
    color: colors.warning,
    fontWeight: '500',
    lineHeight: 15,
  },
  memberShareLabel: {
    fontSize: 10,
    color: colors.textMuted,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
    marginTop: 2,
  },
});

export default getCreateSceneStyles;
