import { StyleSheet } from 'react-native';

export const getScenesScreenStyles = (colors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  listContainer: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 12, paddingBottom: 100 },
  headerSection: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  headerContent: { flex: 1 },
  title: { fontSize: 28, fontWeight: '800', color: colors.text, marginBottom: 4, letterSpacing: -0.5 },
  subtitle: { fontSize: 14, color: colors.textSecondary, fontWeight: '500' },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  headerSearchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surfaceAlt, borderRadius: 20, height: 40, overflow: 'hidden' },
  searchIconButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  searchIconContainer: { width: 28, height: 40, alignItems: 'center', justifyContent: 'center', marginLeft: 6 },
  inputContainer: { flex: 1, height: 40, justifyContent: 'center' },
  headerSearchInput: { flex: 1, fontSize: 14, color: colors.inputText, fontWeight: '500', paddingHorizontal: 2, height: 40 },
  clearButtonContainer: { width: 28, height: 40, alignItems: 'center', justifyContent: 'center' },
  headerClearButton: { width: 24, height: 24, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: 'rgba(100, 116, 139, 0.15)' },
  createButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.primary, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 12, gap: 6, shadowColor: colors.primary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 6 },
  createButtonText: { fontSize: 14, fontWeight: '600', color: '#ffffff' },
  filterSection: { marginBottom: 12 },
  filterContainer: { flexDirection: 'row', gap: 12 },
  filterChip: { backgroundColor: colors.surfaceAlt, borderRadius: 20, paddingHorizontal: 4, paddingVertical: 4, borderWidth: 1, borderColor: colors.cardBorderMedium },
  activeFilterChip: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipContent: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 6, gap: 6 },
  chipText: { fontSize: 14, fontWeight: '600', color: colors.textSecondary },
  activeChipText: { color: '#ffffff' },
  chipBadge: { backgroundColor: colors.skeleton, borderRadius: 10, paddingHorizontal: 6, paddingVertical: 2, minWidth: 20, alignItems: 'center' },
  activeChipBadge: { backgroundColor: 'rgba(255, 255, 255, 0.2)' },
  chipBadgeText: { fontSize: 11, fontWeight: '700', color: colors.textSecondary },
  activeChipBadgeText: { color: '#ffffff' },
  sceneCard: { backgroundColor: colors.card, borderRadius: 16, padding: 20, marginBottom: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 12, elevation: 4, borderWidth: 1, borderColor: colors.cardBorder },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  titleSection: { flex: 1, marginRight: 16 },
  sceneTitle: { fontSize: 18, fontWeight: '700', color: colors.text, marginBottom: 6, letterSpacing: -0.3 },
  groupBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.primaryLight, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, alignSelf: 'flex-start', gap: 4 },
  groupText: { fontSize: 12, color: colors.primary, fontWeight: '600' },
  amountSection: { alignItems: 'flex-end' },
  totalAmount: { fontSize: 20, fontWeight: '800', color: colors.text, letterSpacing: -0.5 },
  totalLabel: { fontSize: 12, color: colors.textSecondary, fontWeight: '500', marginTop: 2 },
  locationRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, gap: 4 },
  locationText: { fontSize: 14, color: colors.textSecondary, fontWeight: '500' },
  description: { fontSize: 14, color: colors.textSecondary, fontWeight: '500', marginBottom: 16, lineHeight: 20 },
  cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 12 },
  dateTimeContainer: { flex: 1 },
  dateTimeRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 4, gap: 6 },
  dateTimeText: { fontSize: 13, color: colors.textSecondary, fontWeight: '500' },
  participantsContainer: { alignItems: 'flex-end' },
  avatarStack: { flexDirection: 'row', marginBottom: 6 },
  avatar: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: colors.card },
  avatarOverlap: { marginLeft: -8 },
  avatarText: { fontSize: 10, fontWeight: '700', color: '#ffffff' },
  avatarMore: { backgroundColor: colors.textSecondary },
  avatarMoreText: { fontSize: 9, fontWeight: '700', color: '#ffffff' },
  participantCount: { fontSize: 12, color: colors.textSecondary, fontWeight: '500' },
  yourShareContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surfaceAlt, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: colors.cardBorderMedium },
  yourShareLabel: { fontSize: 13, color: colors.textSecondary, fontWeight: '500' },
  yourShareAmount: { fontSize: 13, fontWeight: '600', color: colors.text },
  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 60 },
  emptyIconContainer: { width: 120, height: 120, borderRadius: 60, alignItems: 'center', justifyContent: 'center', marginBottom: 24 },
  emptyTitle: { fontSize: 20, fontWeight: '700', color: colors.text, marginBottom: 8, textAlign: 'center' },
  emptySubtitle: { fontSize: 14, color: colors.textSecondary, textAlign: 'center', lineHeight: 20, marginBottom: 32, paddingHorizontal: 32 },
  emptyButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.primary, paddingHorizontal: 24, paddingVertical: 12, borderRadius: 12, gap: 8, shadowColor: colors.primary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 6 },
  emptyButtonText: { fontSize: 16, fontWeight: '600', color: '#ffffff' },
  rightActionsContainer: { flexDirection: 'row', alignItems: 'center', marginTop: 12 },
  actionButton: { width: 80, height: '100%', alignItems: 'center', justifyContent: 'center', gap: 4 },
  editButton: { backgroundColor: '#f59e0b', borderTopLeftRadius: 16, borderBottomLeftRadius: 16 },
  deleteButton: { backgroundColor: '#ef4444', borderTopRightRadius: 16, borderBottomRightRadius: 16 },
  actionButtonText: { fontSize: 12, fontWeight: '600', color: '#ffffff' },
  listFooter: { height: 200 },
});

