import { StyleSheet, Platform } from 'react-native';

export const splashStyles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    flex: 1,
    backgroundColor: '#0891b2',
    zIndex: 9999,
  },
  gradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backgroundElements: {
    ...StyleSheet.absoluteFillObject,
  },
  circle: {
    position: 'absolute',
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  circle1: {
    width: 240,
    height: 240,
    top: -60,
    right: -60,
  },
  circle2: {
    width: 180,
    height: 180,
    bottom: 120,
    left: -40,
  },
  circle3: {
    width: 120,
    height: 120,
    top: '42%',
    right: 10,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
    paddingTop: Platform.OS === 'ios' ? 40 : 20,
  },
  logoContainer: {
    marginBottom: 25,
  },
  logoWrapper: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.35)',
  },
  logoImage: {
    width: 70,
    height: 70,
  },
  animationContainer: {
    marginBottom: 25,
    alignItems: 'center',
    justifyContent: 'center',
    height: 160,
    width: '100%',
  },
  walletAnimationContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 180,
    height: 160,
    position: 'relative',
  },
  walletIcon: {
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  walletBody: {
    width: 84,
    height: 62,
    backgroundColor: '#ffffff',
    borderRadius: 14,
    position: 'relative',
    overflow: 'hidden',
  },
  walletTop: {
    width: '100%',
    height: 10,
    backgroundColor: '#06b6d4',
  },
  walletCards: {
    flex: 1,
    padding: 8,
    justifyContent: 'center',
    gap: 4,
  },
  card: {
    height: 6,
    borderRadius: 2,
  },
  card1: { backgroundColor: '#06b6d4', width: '85%' },
  card2: { backgroundColor: '#0ea5e9', width: '65%' },
  card3: { backgroundColor: '#0891b2', width: '75%' },
  walletShadow: {
    height: 4,
    width: 60,
    backgroundColor: 'rgba(0, 0, 0, 0.15)',
    borderRadius: 10,
    marginTop: 8,
  },
  paymentSymbol: {
    position: 'absolute',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 3,
  },
  symbol1: { top: 10, left: 10 },
  symbol2: { top: 25, right: 10 },
  symbol3: { bottom: 20, left: 15 },
  symbolText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#ffffff',
  },
  floatingElements: {
    ...StyleSheet.absoluteFillObject,
  },
  floatingDot: {
    position: 'absolute',
    borderRadius: 99,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
  },
  floatingDot1: { width: 6, height: 6, top: 20, left: 30 },
  floatingDot2: { width: 8, height: 8, top: 40, right: 35 },
  floatingDot3: { width: 5, height: 5, bottom: 30, left: 40 },
  floatingDot4: { width: 7, height: 7, bottom: 15, right: 45 },
  titleContainer: {
    alignItems: 'center',
    marginBottom: 40,
  },
  appTitle: {
    fontSize: 38,
    fontWeight: '900',
    color: '#ffffff',
    marginBottom: 6,
    letterSpacing: -0.5,
  },
  appSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.95)',
    fontWeight: '600',
    letterSpacing: 3,
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  taglineContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  taglineDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
  },
  taglineText: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.75)',
    fontWeight: '500',
  },
  loadingContainer: {
    alignItems: 'center',
    height: 60,
  },
  loadingTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 14,
  },
  loadingSpinner: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    borderTopColor: '#ffffff',
  },
  loadingText: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.85)',
    fontWeight: '500',
  },
  progressContainer: {
    width: 200,
    height: 4,
  },
  progressBar: {
    width: 200,
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFill: {
    width: 200,
    height: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 2,
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    alignItems: 'center',
  },
  footerText: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.6)',
    fontWeight: '600',
    marginBottom: 2,
  },
  versionText: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.4)',
  },
});
